apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  selector:
      matchLabels:
        name: application-pod-dev
  template:
    metadata:
      labels:
       name: application-pod-dev
    spec:
      containers:
        - name: cntr-story-app
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80