apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv2-deployment
spec:
  selector:
      matchLabels:
        name: appv2-pod-dev
  template:
    metadata:
      labels:
       name: appv2-pod-dev
    spec:
      containers:
        - name: container-appv2
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80