apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  selector:
      matchLabels:
        name: app-pod
  template:
    metadata:
      labels:
       name: app-pod
    spec:
      containers:
        - name: container-loja-app
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80